language: python
python:
  - "3.7.0"  
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest-cov codecov
# command to run tests
script:
  - pytest --cov=src # or py.test for Python versions 3.5 and below
  #- py.test # or py.test for Python versions 3.5 and below
after_success:
  - codecov
